tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"

brew "direnv"
brew "ffmpeg"
brew "hub"
brew "jq"
brew "nkf"
brew "shellcheck"
brew "node"
brew "hadolint"

cask "google-chrome"
cask "1password"
cask "slack"
cask "alfred"
cask "docker"
cask "iterm"
cask "karabiner-elements"
cask "scroll-reverser"
cask "rectangle"
cask "gitkraken"
cask "coteditor"
cask "java"
cask "font-ricty-diminished"

mas "Bear", id: 1091189122
mas "Dato", id: 1470584107
mas "Reeder", id: 880001334
