brew "coreutils"
brew "arp-scan"
brew "awscli"
brew "ctags"
brew "curl"
brew "direnv"
brew "ffmpeg"
brew "fzf"
brew "jq"
brew "nkf"
brew "rename"
brew "stow"
brew "tree"
brew "vifm"
brew "watch"
brew "jpeg"
brew "hub"

brew "macvim", link: false
cask "alfred"
cask "karabiner-elements"
cask "macvim"
cask "skitch"
cask "slack"
cask "vlc"

mas "Be Focused", id: 973134470
mas "Bear", id: 1091189122
mas "GIF Brewery 3", id: 1081413713
mas "Reeder", id: 880001334
